/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/lab.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/lab.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.012}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Circle_green_tube_0.geometry} material={materials.green_tube} />
            <mesh geometry={nodes.Circle_metal_0.geometry} material={materials.metal} />
          </group>
          <group position={[0.045, 1.063, -235.93]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cube_metal_0.geometry} material={materials.metal} />
            <mesh geometry={nodes.Cube_screen_0.geometry} material={materials.screen} />
          </group>
          <mesh geometry={nodes.BezierCurve_piping_0.geometry} material={materials.piping} position={[-171.294, 51.191, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Circle002_green_tube_0.geometry} material={materials.green_tube} position={[-222.128, 91.56, 59.272]} rotation={[-Math.PI / 2, 0, 0]} scale={14.491} />
          <mesh geometry={nodes.Circle003_lights_0.geometry} material={materials.lights} position={[0, 40.986, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube001_keys_0.geometry} material={materials.keys} position={[-30.633, 75.431, -180.458]} rotation={[-1.264, 0, 0]} scale={1.759} />
          <mesh geometry={nodes.Cube002_metal_0.geometry} material={materials.metal} position={[-230.145, 99.171, 15.06]} rotation={[-Math.PI / 2, 0, 0]} scale={[21.966, 100, 100]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/lab.glb')
