/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/position.glb -K -k 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/position.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Light" position={[-49.778, 1554.62, 230.75]} rotation={[1.839, 0.499, 2.828]} scale={100}>
          <group name="Object_8" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_9" />
          </group>
        </group>
        <group name="Sketchfab_model" position={[0.258, 1.418, 1.73]} rotation={[-Math.PI / 2, 0, 0]} scale={0.02}>
          <group name="1f274e8754eb4551be271056d7532441fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode">
              <group name="ball" position={[-482.963, 496.695, 488.044]} rotation={[-Math.PI / 2, 0, 0]} scale={37.472}>
                <mesh name="ball_ball_0" geometry={nodes.ball_ball_0.geometry} material={materials.ball} />
              </group>
              <group name="board" position={[-722.695, 925.494, -1064.587]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="board_dark_blue_0" geometry={nodes.board_dark_blue_0.geometry} material={materials.dark_blue} />
              </group>
              <group name="board001" position={[-722.877, 921.404, -1073.86]} scale={76.649}>
                <mesh name="board001_Material004_0" geometry={nodes.board001_Material004_0.geometry} material={materials['Material.016']} />
              </group>
              <group name="board007" position={[-665.007, 845.834, -1072.364]} scale={4.036}>
                <mesh name="board007_red_0" geometry={nodes.board007_red_0.geometry} material={materials['material.001']} />
              </group>
              <group name="board009" position={[-722.877, 921.404, -1073.86]} scale={76.649}>
                <mesh name="board009_wood001_0" geometry={nodes.board009_wood001_0.geometry} material={materials['wood.001']} />
              </group>
              <group name="board010" position={[-722.877, 921.404, -1073.86]} scale={76.649}>
                <mesh name="board010_wood002_0" geometry={nodes.board010_wood002_0.geometry} material={materials['wood.002']} />
              </group>
              <group name="board_2" position={[-1087.236, 828.398, -678.823]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[23.629, 12.891, 73.549]}>
                <mesh name="board_2_tube_0" geometry={nodes.board_2_tube_0.geometry} material={materials.tube} />
              </group>
              <group name="board_2001" position={[-1087.224, 964.043, -705.267]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={70.782}>
                <mesh name="board_2001_green003_0" geometry={nodes.board_2001_green003_0.geometry} material={materials['green.003']} />
              </group>
              <group name="board_2002" position={[-1087.223, 832.195, -593.806]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={27.343}>
                <mesh name="board_2002_green002_0" geometry={nodes.board_2002_green002_0.geometry} material={materials['green.002']} />
              </group>
              <group name="board_2003" position={[-1087.223, 826.895, -768.702]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={34.756}>
                <mesh name="board_2003_green002_0" geometry={nodes.board_2003_green002_0.geometry} material={materials['green.002']} />
              </group>
              <group name="board_2004" position={[-1087.223, 879.894, -859.683]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={33.766}>
                <mesh name="board_2004_green002_0" geometry={nodes.board_2004_green002_0.geometry} material={materials['green.002']} />
              </group>
              <group name="board_2005" position={[-1087.223, 1004.441, -598.223]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={24.968}>
                <mesh name="board_2005_green002_0" geometry={nodes.board_2005_green002_0.geometry} material={materials['green.002']} />
              </group>
              <group name="board_2006" position={[-1080.009, 1088.814, -895.494]} rotation={[-Math.PI / 2, 0, 0]} scale={16.854}>
                <mesh name="board_2006_metalic001_0" geometry={nodes.board_2006_metalic001_0.geometry} material={materials['metalic.001']} />
              </group>
              <group name="board_2007" position={[-1100.842, 919.481, -730.763]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[161.545, 221.435, 100]}>
                <mesh name="board_2007_wood002_0" geometry={nodes.board_2007_wood002_0.geometry} material={materials['wood.002']} />
              </group>
              <group name="board_2008" position={[-1100.842, 919.481, -730.763]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[161.545, 221.435, 100]}>
                <mesh name="board_2008_green_0" geometry={nodes.board_2008_green_0.geometry} material={materials.green} />
              </group>
              <group name="board_2009" position={[-1100.842, 919.481, -730.763]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[161.545, 221.435, 100]}>
                <mesh name="board_2009_wood002_0" geometry={nodes.board_2009_wood002_0.geometry} material={materials['wood.002']} />
              </group>
              <group name="board_2010" position={[-1087.236, 1030.21, -855.485]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[32.127, 17.527, 100]}>
                <mesh name="board_2010_pink_0" geometry={nodes.board_2010_pink_0.geometry} material={materials.pink} />
              </group>
              <group name="board_2011" position={[-1080.009, 1088.814, -895.494]} rotation={[-Math.PI / 2, 0, 0]} scale={16.854}>
                <mesh name="board_2011_red_0" geometry={nodes.board_2011_red_0.geometry} material={materials['material.001']} />
              </group>
              <group name="box" position={[-415.612, -8.035, 674.445]} rotation={[-Math.PI / 2, 0, 0.353]} scale={[146.355, 80.357, 100]}>
                <mesh name="box_wood002_0" geometry={nodes.box_wood002_0.geometry} material={materials['wood.002']} />
              </group>
              <group name="box001" position={[306.608, -5.305, 684.039]} rotation={[-Math.PI / 2, 0, -0.502]} scale={[100.782, 55.335, 68.861]}>
                <mesh name="box001_pink_0" geometry={nodes.box001_pink_0.geometry} material={materials.pink} />
              </group>
              <group name="cap" position={[-949.856, 620.771, 11.792]} rotation={[-Math.PI / 2, 0, 0]} scale={26.766}>
                <mesh name="cap_red_0" geometry={nodes.cap_red_0.geometry} material={materials['material.001']} />
              </group>
              <group name="cap001" position={[-714.775, 461.246, 467.888]} rotation={[-Math.PI / 2, 0, 0]} scale={39.754}>
                <mesh name="cap001_red_0" geometry={nodes.cap001_red_0.geometry} material={materials['material.001']} />
              </group>
              <group name="chair" position={[-52.287, 17.147, -292.806]} rotation={[-Math.PI / 2, 0, 0.788]} scale={31.781}>
                <group name="Plane006" position={[0, 0, 8.243]} scale={4.332} />
                <group name="Plane007_2" position={[2.796, 0, 14.675]} rotation={[0, 1.571, 0]} scale={4.332} />
                <group name="Plane008" position={[3.48, 0, 7.559]} scale={1.137}>
                  <group name="Plane008_metalic_0" position={[-9.201, 3.926, 0.445]} rotation={[0, 0, -2.352]}>
                    <mesh name="Plane008_metalic_0_1" geometry={nodes.Plane008_metalic_0_1.geometry} material={materials.metalic} />
                    <mesh name="Plane008_metalic_0_2" geometry={nodes.Plane008_metalic_0_2.geometry} material={materials['material.001']} />
                  </group>
                </group>
              </group>
              <group name="Circle002" position={[-408.324, 473.799, 514.239]} rotation={[Math.PI, 0.773, 1.988]} scale={11.24}>
                <mesh name="Circle002_metalic_0" geometry={nodes.Circle002_metalic_0.geometry} material={materials.metalic} />
              </group>
              <group name="Circle013" position={[-408.324, 473.799, 514.239]} rotation={[Math.PI, 0.773, 1.988]} scale={11.24}>
                <mesh name="Circle013_red_0" geometry={nodes.Circle013_red_0.geometry} material={materials['material.001']} />
              </group>
              <group name="clock001" position={[-26.929, 1240.219, -1073.332]} scale={100}>
                <mesh name="clock001_Material004_0" geometry={nodes.clock001_Material004_0.geometry} material={materials['Material.016']} />
              </group>
              <group name="clock002" position={[-26.929, 1240.219, -1073.332]} scale={3.352}>
                <mesh name="clock002_dark_blue_0" geometry={nodes.clock002_dark_blue_0.geometry} material={materials.dark_blue} />
              </group>
              <group name="clock003" position={[-26.965, 1239.981, -1057.545]} rotation={[0, 0, 2.924]} scale={3.151}>
                <mesh name="clock003_dark_blue_0" geometry={nodes.clock003_dark_blue_0.geometry} material={materials.dark_blue} />
              </group>
              <group name="clock004" position={[-26.929, 1240.219, -1073.332]} scale={100}>
                <mesh name="clock004_green001_0" geometry={nodes.clock004_green001_0.geometry} material={materials['green.001']} />
              </group>
              <group name="Cylinder" position={[-438.028, 468.543, 409.931]} rotation={[-0.09, 0.434, 0.038]} scale={[12.271, 12.271, 19.476]}>
                <mesh name="Cylinder_cap_0" geometry={nodes.Cylinder_cap_0.geometry} material={materials.material_7} />
              </group>
              <group name="Cylinder001" position={[-438.028, 468.543, 409.931]} rotation={[-0.09, 0.434, 0.038]} scale={[12.271, 12.271, 19.476]}>
                <mesh name="Cylinder001_tube_0" geometry={nodes.Cylinder001_tube_0.geometry} material={materials.tube} />
              </group>
              <group name="file001" position={[-932.835, 461.359, -255.656]} rotation={[-Math.PI / 2, 0, 0]} scale={141.36}>
                <group name="file" position={[-0.034, 0, 0]}>
                  <mesh name="file_gray_0" geometry={nodes.file_gray_0.geometry} material={materials.gray} />
                </group>
                <mesh name="file001_dark_blue_0" geometry={nodes.file001_dark_blue_0.geometry} material={materials.dark_blue} />
              </group>
              <group name="file002" position={[-954.72, 461.196, 160.801]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 287.658, 100]}>
                <group name="Circle006" position={[1.055, -0.732, 1.167]} rotation={[0, 1.571, 0]} scale={[0.075, 0.026, 0.075]}>
                  <mesh name="Circle006_blue_0" geometry={nodes.Circle006_blue_0.geometry} material={materials.blue} />
                </group>
                <mesh name="file002_green002_0" geometry={nodes.file002_green002_0.geometry} material={materials['green.002']} />
              </group>
              <group name="file003" position={[-954.72, 461.196, 160.801]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 287.658, 100]}>
                <mesh name="file003_green003_0" geometry={nodes.file003_green003_0.geometry} material={materials['green.003']} />
              </group>
              <group name="flask" position={[-860.03, 321.412, -772.648]} rotation={[-Math.PI / 2, 0, 0]} scale={104.449}>
                <mesh name="flask_metalic_0" geometry={nodes.flask_metalic_0.geometry} material={materials.metalic} />
              </group>
              <group name="flask001" position={[-860.134, 546.534, -672.779]} rotation={[-Math.PI / 2, 0, 0]} scale={4.158}>
                <mesh name="flask001_glass_0" geometry={nodes.flask001_glass_0.geometry} material={materials.glass} />
              </group>
              <group name="flask002" position={[-947.484, 819.966, -842.689]} rotation={[-Math.PI / 2, 0, 0]} scale={6.162}>
                <mesh name="flask002_wood002_0" geometry={nodes.flask002_wood002_0.geometry} material={materials['wood.002']} />
              </group>
              <group name="flask003" position={[-860.216, 546.534, -657.351]} rotation={[-Math.PI / 2, 0, 0]} scale={4.158}>
                <mesh name="flask003_glass_0" geometry={nodes.flask003_glass_0.geometry} material={materials.glass} />
              </group>
              <group name="flask004" position={[-947.44, 687.337, -645.16]} rotation={[-Math.PI / 2, 0, 0]} scale={6.162}>
                <mesh name="flask004_wood002_0" geometry={nodes.flask004_wood002_0.geometry} material={materials['wood.002']} />
              </group>
              <group name="flask005" position={[-860.546, 546.534, -688.119]} rotation={[-Math.PI / 2, 0, 0]} scale={4.158}>
                <mesh name="flask005_glass_0" geometry={nodes.flask005_glass_0.geometry} material={materials.glass} />
              </group>
              <group name="flask006" position={[-949.97, 537.211, -843.809]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="flask006_metalic_0" geometry={nodes.flask006_metalic_0.geometry} material={materials.metalic} />
              </group>
              <group name="flask007" position={[-949.97, 402.293, -646.442]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="flask007_metalic_0" geometry={nodes.flask007_metalic_0.geometry} material={materials.metalic} />
              </group>
              <group name="flask008" position={[-947.488, 703.089, -842.682]} rotation={[-Math.PI / 2, 0, 0]} scale={49.548}>
                <mesh name="flask008_glass_0" geometry={nodes.flask008_glass_0.geometry} material={materials.glass} />
              </group>
              <group name="flask009" position={[-947.488, 568.17, -645.315]} rotation={[-Math.PI / 2, 0, 0]} scale={49.548}>
                <mesh name="flask009_glass_0" geometry={nodes.flask009_glass_0.geometry} material={materials.glass} />
              </group>
              <group name="flask010" position={[-966.601, 461.216, -992.767]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="flask010_metalic_0" geometry={nodes.flask010_metalic_0.geometry} material={materials.metalic} />
              </group>
              <group name="flask011" position={[-1003.81, 461.206, -979.988]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="flask011_wood005_0" geometry={nodes.flask011_wood005_0.geometry} material={materials['wood.005']} />
              </group>
              <group name="flask012" position={[-947.488, 568.17, -645.315]} rotation={[-Math.PI / 2, 0, 0]} scale={45.299}>
                <mesh name="flask012_liquid_0" geometry={nodes.flask012_liquid_0.geometry} material={materials.liquid} />
              </group>
              <group name="flask013" position={[-947.488, 703.325, -842.853]} rotation={[-Math.PI / 2, 0, 0]} scale={45.299}>
                <mesh name="flask013_liquid001_0" geometry={nodes.flask013_liquid001_0.geometry} material={materials['liquid.001']} />
              </group>
              <group name="hat001" position={[-349.026, 453.992, 601.078]} rotation={[-Math.PI / 2, 0, 2.025]} scale={86.337}>
                <group name="hat" position={[0, -0.031, 0]}>
                  <mesh name="hat_metalic_0" geometry={nodes.hat_metalic_0.geometry} material={materials.metalic} />
                </group>
                <group name="hat002" position={[0.155, -0.155, 1.164]} rotation={[0.245, 0.234, 0.086]} scale={0.117}>
                  <mesh name="hat002_red_0" geometry={nodes.hat002_red_0.geometry} material={materials['material.001']} />
                </group>
                <group name="hat003" position={[-0.646, -0.368, 0.926]} rotation={[0.29, -0.764, 0.217]} scale={0.117}>
                  <mesh name="hat003_red_0" geometry={nodes.hat003_red_0.geometry} material={materials['material.001']} />
                </group>
                <group name="hat004" position={[0.661, 0.351, 0.916]} rotation={[-0.29, 0.764, 0.217]} scale={0.117}>
                  <mesh name="hat004_red_0" geometry={nodes.hat004_red_0.geometry} material={materials['material.001']} />
                </group>
                <group name="hat005" position={[0.367, -0.677, 0.894]} rotation={[Math.PI / 4, 0.208, -0.347]} scale={0.117}>
                  <mesh name="hat005_red_0" geometry={nodes.hat005_red_0.geometry} material={materials['material.001']} />
                </group>
                <group name="hat006" position={[-0.15, 0.696, 0.941]} rotation={[-Math.PI / 4, -0.208, -0.347]} scale={0.117}>
                  <mesh name="hat006_red_0" geometry={nodes.hat006_red_0.geometry} material={materials['material.001']} />
                </group>
                <group name="hat007" position={[0.155, -0.155, 1.164]} rotation={[0.245, 0.234, 0.086]} scale={0.117}>
                  <mesh name="hat007_dark_blue_0" geometry={nodes.hat007_dark_blue_0.geometry} material={materials.dark_blue} />
                </group>
                <group name="hat008" position={[0.367, -0.677, 0.894]} rotation={[Math.PI / 4, 0.208, -0.347]} scale={0.117}>
                  <mesh name="hat008_dark_blue_0" geometry={nodes.hat008_dark_blue_0.geometry} material={materials.dark_blue} />
                </group>
                <group name="hat009" position={[0.661, 0.351, 0.916]} rotation={[-0.29, 0.764, 0.217]} scale={0.117}>
                  <mesh name="hat009_dark_blue_0" geometry={nodes.hat009_dark_blue_0.geometry} material={materials.dark_blue} />
                </group>
                <group name="hat010" position={[-0.646, -0.368, 0.926]} rotation={[0.29, -0.764, 0.217]} scale={0.117}>
                  <mesh name="hat010_dark_blue_0" geometry={nodes.hat010_dark_blue_0.geometry} material={materials.dark_blue} />
                </group>
                <group name="hat011" position={[-0.15, 0.696, 0.941]} rotation={[-Math.PI / 4, -0.208, -0.347]} scale={0.117}>
                  <mesh name="hat011_dark_blue_0" geometry={nodes.hat011_dark_blue_0.geometry} material={materials.dark_blue} />
                </group>
                <mesh name="hat001_metalic_0" geometry={nodes.hat001_metalic_0.geometry} material={materials.metalic} />
              </group>
              <group name="lamp001" position={[-829.455, 461.197, 611.593]} rotation={[-Math.PI / 2, 0, 0.873]} scale={[68.198, 123.959, 123.959]}>
                <group name="lamp" position={[-0.903, 0.002, 0.227]} scale={[1.818, 1, 1]}>
                  <mesh name="lamp_green001_0" geometry={nodes.lamp_green001_0.geometry} material={materials['green.001']} />
                </group>
                <group name="lamp002" position={[0.828, 0.009, 2.563]} scale={[0.968, 0.919, 1]}>
                  <mesh name="lamp002_green_0" geometry={nodes.lamp002_green_0.geometry} material={materials.green} />
                </group>
                <group name="lamp003" position={[0, 0.727, 0]}>
                  <mesh name="lamp003_green001_0" geometry={nodes.lamp003_green001_0.geometry} material={materials['green.001']} />
                </group>
                <mesh name="lamp001_green_0" geometry={nodes.lamp001_green_0.geometry} material={materials.green} />
              </group>
              <group name="pin007" position={[-1051.908, 441.39, 789.964]} rotation={[0.023, 0, 0]} scale={11.434}>
                <mesh name="pin007_metalic_0" geometry={nodes.pin007_metalic_0.geometry} material={materials.metalic} />
              </group>
              <group name="Plane" position={[-926.294, 620.452, 337.732]} rotation={[-Math.PI / 2, 0, 0.582]} scale={[20.722, 37.614, 37.614]}>
                <mesh name="Plane_wood004_0" geometry={nodes.Plane_wood004_0.geometry} material={materials['wood.004']} />
              </group>
              <group name="Plane009" position={[-238.144, 461.241, 425.733]} rotation={[-Math.PI / 2, 0, -0.592]} scale={49.631}>
                <mesh name="Plane009_triangle_0" geometry={nodes.Plane009_triangle_0.geometry} material={materials.triangle} />
              </group>
              <group name="poster" position={[578.558, 1022.056, -1073.542]} scale={100}>
                <mesh name="poster_wood001_0" geometry={nodes.poster_wood001_0.geometry} material={materials['wood.001']} />
              </group>
              <group name="receiver" position={[-948.704, 461.329, -889.338]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 165.714, 100]}>
                <group name="Circle" position={[1, 0.249, 0.831]} rotation={[0, 1.571, 0]} scale={[0.258, 0.156, 0.258]}>
                  <mesh name="Circle_green003_0" geometry={nodes.Circle_green003_0.geometry} material={materials['green.003']} />
                </group>
                <group name="Plane001" position={[0.953, -0.858, 0.233]} rotation={[0, 1.571, 0]} scale={[0.094, 0.057, 0.094]}>
                  <mesh name="Plane001_green003_0" geometry={nodes.Plane001_green003_0.geometry} material={materials['green.003']} />
                </group>
                <mesh name="receiver_green002_0" geometry={nodes.receiver_green002_0.geometry} material={materials['green.002']} />
              </group>
              <group name="receiver001" position={[-715.007, 461.329, -984.529]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[49.336, 81.757, 49.336]}>
                <group name="Circle001" position={[1, -0.592, 1.055]} rotation={[-1.546, 1.163, -0.507]} scale={[0.329, 0.428, 0.462]}>
                  <mesh name="Circle001_green001_0" geometry={nodes.Circle001_green001_0.geometry} material={materials['green.001']} />
                </group>
                <group name="pin001" position={[5.286, -1.844, 0.243]} rotation={[0, 1.571, 0]} scale={[0.057, 0.034, 0.057]}>
                  <mesh name="pin001_metalic_0" geometry={nodes.pin001_metalic_0.geometry} material={materials.metalic} />
                </group>
                <group name="pin005" position={[-0.829, 1, 0.157]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[0.057, 0.057, 0.034]}>
                  <mesh name="pin005_metalic_0" geometry={nodes.pin005_metalic_0.geometry} material={materials.metalic} />
                </group>
                <group name="Plane003" position={[0.953, -0.107, 1.053]} rotation={[0, Math.PI / 2, 0]} scale={[0.094, 0.057, 0.094]}>
                  <mesh name="Plane003_green001_0" geometry={nodes.Plane003_green001_0.geometry} material={materials['green.001']} />
                </group>
                <mesh name="receiver001_green_0" geometry={nodes.receiver001_green_0.geometry} material={materials.green} />
              </group>
              <group name="reel001" position={[-1078.792, 1088.817, -649.135]} rotation={[-Math.PI / 2, 0, 0.331]} scale={17.988}>
                <group name="Vert002" position={[-0.912, -0.175, 3.394]} rotation={[0, 0, 0.331]} scale={5.559}>
                  <mesh name="Vert002_red_0" geometry={nodes.Vert002_red_0.geometry} material={materials['material.001']} />
                </group>
                <mesh name="reel001_red_0" geometry={nodes.reel001_red_0.geometry} material={materials['material.001']} />
                <mesh name="reel001_red_0001" geometry={nodes.reel001_red_0001.geometry} material={materials['material.001']} />
              </group>
              <group name="reel002" position={[-1078.792, 1088.817, -582.651]} rotation={[-Math.PI / 2, 0, 0]} scale={17.988}>
                <group name="reel" position={[-0.872, -0.059, 3.394]} scale={5.559}>
                  <mesh name="reel_red_0" geometry={nodes.reel_red_0.geometry} material={materials['material.001']} />
                </group>
                <mesh name="reel002_red_0" geometry={nodes.reel002_red_0.geometry} material={materials['material.001']} />
                <mesh name="reel002_red_0001" geometry={nodes.reel002_red_0001.geometry} material={materials['material.001']} />
              </group>
              <group name="reel003" position={[-1078.792, 1088.817, -582.651]} rotation={[-Math.PI / 2, 0, 0]} scale={17.988}>
                <mesh name="reel003_metalic001_0" geometry={nodes.reel003_metalic001_0.geometry} material={materials['metalic.001']} />
              </group>
              <group name="reel004" position={[-1078.792, 1088.817, -649.135]} rotation={[-Math.PI / 2, 0, 0.331]} scale={17.988}>
                <mesh name="reel004_metalic001_0" geometry={nodes.reel004_metalic001_0.geometry} material={materials['metalic.001']} />
              </group>
              <group name="stand" position={[-924.989, 419.31, -939.469]} rotation={[-Math.PI / 2, 0, 0]} scale={339.799}>
                <group name="legs" position={[2.653, -4.849, -1.184]} scale={0.071}>
                  <mesh name="legs_wood001_0" geometry={nodes.legs_wood001_0.geometry} material={materials['wood.001']} />
                </group>
                <group name="Plane002" position={[-0.081, 0, 0]}>
                  <mesh name="Plane002_gray_0" geometry={nodes.Plane002_gray_0.geometry} material={materials.gray} />
                </group>
                <group name="Plane004" position={[-0.219, 1.497, -0.384]} scale={1.458}>
                  <mesh name="Plane004_blue_0" geometry={nodes.Plane004_blue_0.geometry} material={materials.blue} />
                </group>
                <mesh name="stand_dark_blue_0" geometry={nodes.stand_dark_blue_0.geometry} material={materials.dark_blue} />
              </group>
              <group name="stand001" position={[-924.989, 419.31, -939.469]} rotation={[-Math.PI / 2, 0, 0]} scale={339.799}>
                <mesh name="stand001_blue_0" geometry={nodes.stand001_blue_0.geometry} material={materials.blue} />
              </group>
              <group name="walls" position={[0, 1092.866, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[1100.927, 1100.926, 1100.926]} />
              <group name="walls001" position={[0, 1092.866, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[1100.927, 1100.926, 1100.926]} />
              <group name="walls002" position={[0, 1092.866, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[1100.927, 1100.926, 1100.926]} />
              <group name="walls003" position={[0, 1092.866, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[1100.927, 1100.926, 1100.926]} />
              <group name="walls004" position={[0, 1092.866, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[1100.927, 1100.926, 1100.926]}>
                <mesh name="walls004_gray_0" geometry={nodes.walls004_gray_0.geometry} material={materials.gray} />
              </group>
              <group name="walls005" position={[0, 1092.866, -0.911]} rotation={[-Math.PI / 2, 0, 0]} scale={[1100.927, 1093.52, 1100.926]}>
                <mesh name="walls005_green004_0" geometry={nodes.walls005_green004_0.geometry} material={materials['green.004']} />
              </group>
              <group name="walls006" position={[0, 1092.866, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[1100.927, 1100.926, 1100.926]}>
                <mesh name="walls006_glass_0" geometry={nodes.walls006_glass_0.geometry} material={materials.glass} />
              </group>
              <group name="washbasin" position={[152.46, 468.879, -1034.332]} scale={28.898}>
                <mesh name="washbasin_metalic_0" geometry={nodes.washbasin_metalic_0.geometry} material={materials.metalic} />
              </group>
              <group name="washbasin001" position={[201.779, 468.879, -1034.332]} scale={15.087}>
                <mesh name="washbasin001_metalic_0" geometry={nodes.washbasin001_metalic_0.geometry} material={materials.metalic} />
              </group>
              <group name="washbasin002" position={[156.188, 340.389, -861.235]} rotation={[-Math.PI / 2, 0, 0]} scale={[211.978, 211.977, 211.977]}>
                <mesh name="washbasin002_ballon_0" geometry={nodes.washbasin002_ballon_0.geometry} material={materials.ballon} />
              </group>
              <group name="washbasin006" position={[320.445, 132.698, -722.708]} rotation={[-Math.PI / 2, 0, 0]} scale={4.586}>
                <mesh name="washbasin006_wood_0" geometry={nodes.washbasin006_wood_0.geometry} material={materials.wood} />
              </group>
              <group name="washbasin008" position={[156.188, 340.389, -861.235]} rotation={[-Math.PI / 2, 0, 0]} scale={[211.978, 211.977, 211.977]}>
                <mesh name="washbasin008_pink_0" geometry={nodes.washbasin008_pink_0.geometry} material={materials.pink} />
              </group>
              <group name="washing_machine" position={[551.44, 516.894, -1007.382]} rotation={[-0.907, 0, 0]} scale={28.43}>
                <mesh name="washing_machine_cap_0" geometry={nodes.washing_machine_cap_0.geometry} material={materials.material_7} />
              </group>
              <group name="washing_machine001" position={[551.44, 516.894, -1007.382]} rotation={[-0.907, 0, 0]} scale={28.43}>
                <mesh name="washing_machine001_Material003_0" geometry={nodes.washing_machine001_Material003_0.geometry} material={materials['Material.017']} />
              </group>
              <group name="washing_machine002" position={[519.324, 56.928, -604.576]} scale={22.488}>
                <mesh name="washing_machine002_Material003_0" geometry={nodes.washing_machine002_Material003_0.geometry} material={materials['Material.017']} />
              </group>
              <group name="washing_machine003" position={[551.44, 516.894, -1007.382]} rotation={[-0.907, 0, 0]} scale={28.43}>
                <mesh name="washing_machine003_Material003_0" geometry={nodes.washing_machine003_Material003_0.geometry} material={materials['Material.017']} />
              </group>
              <group name="washing_machine004" position={[684.725, 229.625, -838.288]} rotation={[-Math.PI / 2, 0, 0]} scale={234.225}>
                <mesh name="washing_machine004_Material002_0" geometry={nodes.washing_machine004_Material002_0.geometry} material={materials['Material.018']} />
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model001" position={[-6.015, 10.74, -15.775]} rotation={[-Math.PI / 2, 0, 0]} scale={3.349}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="cabel1_3" position={[-1.095, 0, 0.309]} />
              <group name="cabel2_4" position={[0.864, 0, -1.493]} />
              <group name="keyboard001_5" position={[-0.241, 0.102, 0.662]}>
                <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.base} position={[0.233, -0.034, 0.353]} />
              </group>
              <group name="keyboard002_7" position={[-0.05, 0.087, -0.573]}>
                <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.base} />
              </group>
              <group name="keyboard_1" position={[-0.241, 0.102, 0.662]}>
                <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.base} position={[0.232, -0.04, 0.36]} />
              </group>
              <group name="monitor001_8" position={[0.175, 0.884, -0.257]} scale={1.002}>
                <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials.base} position={[-0.096, 0, 0.653]} />
              </group>
              <group name="monitor_0" position={[-0.135, 1.001, -0.781]}>
                <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.base} position={[0.178, -0.033, 0.654]} />
              </group>
              <group name="mouse001_6" position={[0.82, 0.096, 0.29]}>
                <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.base} position={[0.13, -0.025, 0.654]} />
              </group>
              <group name="mouse_2" position={[0.82, 0.096, 0.29]}>
                <mesh name="Object_8001" geometry={nodes.Object_8001.geometry} material={materials.base} position={[0.122, -0.033, 0.619]} />
              </group>
            </group>
          </group>
        </group>
        <group name="Armature" position={[-5.896, 5.87, -5.559]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.051}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="Cube" geometry={nodes.Cube.geometry} material={materials['Material.006']} skeleton={nodes.Cube.skeleton} />
          <group name="Cube001">
            <skinnedMesh name="Cube001_1" geometry={nodes.Cube001_1.geometry} material={materials['Material.005']} skeleton={nodes.Cube001_1.skeleton} />
            <skinnedMesh name="Cube001_2" geometry={nodes.Cube001_2.geometry} material={materials['Material.003']} skeleton={nodes.Cube001_2.skeleton} />
            <skinnedMesh name="Cube001_3" geometry={nodes.Cube001_3.geometry} material={materials['Material.004']} skeleton={nodes.Cube001_3.skeleton} />
            <skinnedMesh name="Cube001_4" geometry={nodes.Cube001_4.geometry} material={materials['Material.007']} skeleton={nodes.Cube001_4.skeleton} />
          </group>
          <group name="Cylinder002">
            <skinnedMesh name="Cylinder002_1" geometry={nodes.Cylinder002_1.geometry} material={materials['Material.005']} skeleton={nodes.Cylinder002_1.skeleton} />
            <skinnedMesh name="Cylinder002_2" geometry={nodes.Cylinder002_2.geometry} material={materials['Material.009']} skeleton={nodes.Cylinder002_2.skeleton} />
            <skinnedMesh name="Cylinder002_3" geometry={nodes.Cylinder002_3.geometry} material={materials['Material.010']} skeleton={nodes.Cylinder002_3.skeleton} />
            <skinnedMesh name="Cylinder002_4" geometry={nodes.Cylinder002_4.geometry} material={materials['Material.011']} skeleton={nodes.Cylinder002_4.skeleton} />
          </group>
          <group name="Göz001">
            <skinnedMesh name="Sphere001" geometry={nodes.Sphere001.geometry} material={materials['Material.012']} skeleton={nodes.Sphere001.skeleton} />
            <skinnedMesh name="Sphere001_1" geometry={nodes.Sphere001_1.geometry} material={materials['Material.013']} skeleton={nodes.Sphere001_1.skeleton} />
            <skinnedMesh name="Sphere001_2" geometry={nodes.Sphere001_2.geometry} material={materials['Material.014']} skeleton={nodes.Sphere001_2.skeleton} />
          </group>
          <skinnedMesh name="Kafa001" geometry={nodes.Kafa001.geometry} material={materials.Face} skeleton={nodes.Kafa001.skeleton} />
          <skinnedMesh name="Kaş" geometry={nodes.Kaş.geometry} material={materials.Saç} skeleton={nodes.Kaş.skeleton} />
          <skinnedMesh name="Kulak001" geometry={nodes.Kulak001.geometry} material={materials['Material.002']} skeleton={nodes.Kulak001.skeleton} />
          <group name="Plane005">
            <skinnedMesh name="Plane009_1" geometry={nodes.Plane009_1.geometry} material={materials['Material.008']} skeleton={nodes.Plane009_1.skeleton} />
            <skinnedMesh name="Plane009_2" geometry={nodes.Plane009_2.geometry} material={materials['Material.015']} skeleton={nodes.Plane009_2.skeleton} />
          </group>
          <group name="Plane010">
            <skinnedMesh name="Plane007" geometry={nodes.Plane007.geometry} material={materials['Material.008']} skeleton={nodes.Plane007.skeleton} />
            <skinnedMesh name="Plane007_1" geometry={nodes.Plane007_1.geometry} material={materials['Material.015']} skeleton={nodes.Plane007_1.skeleton} />
          </group>
          <skinnedMesh name="SAç001" geometry={nodes.SAç001.geometry} material={materials['Material.001']} skeleton={nodes.SAç001.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/position.glb')
