/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Viktor_ (https://sketchfab.com/Viktor.Zhuravlev)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/notice-board-low-poly-c7253f06bb8c49b0afcd60a509a8240c
Title: Notice board low-poly
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Board(props) {
  const { nodes, materials } = useGLTF("models/board.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube__0.geometry}
          material={materials["Scene_-_Root"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
      </group>
    </group>
  );
}

useGLTF.preload("models/board.glb");
