/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useAnimations, useFBX, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { Leva, useControls } from "leva";
import * as THREE from "three";

export function Boy(props) {
  const { animation } = props;
  const { headFollow, cursorFollow, wireframe } = useControls({
    headFollow: false,
    cursorFollow: false,
    wireframe: false,
  });
  const group = useRef();
  const { nodes, materials } = useGLTF("models/kid.glb");

  const { animations: typingAnimation } = useFBX("animations/Typing.fbx");
  const { animations: standingAnimation } = useFBX("animations/Standing.fbx");
  const { animations: fallingAnimation } = useFBX("animations/Falling.fbx");
  const { animations: nervousAnimation } = useFBX("animations/Nervous.fbx");

  typingAnimation[0].name = "Typing";
  standingAnimation[0].name = "Standing";
  fallingAnimation[0].name = "Falling";
  nervousAnimation[0].name = "Nervous";

  const { actions } = useAnimations(
    [
      typingAnimation[0],
      standingAnimation[0],
      fallingAnimation[0],
      nervousAnimation[0],
    ],
    group
  );

  useEffect(() => {
    actions[animation].reset().fadeIn(0.5).play();
    return () => {
      actions[animation].reset().fadeOut(0.5);
    };
  }, [animation]);
  useEffect(() => {
    Object.values(materials).forEach((material) => {
      material.wireframe = wireframe;
    });
  }, [wireframe]);

  return (
    <>
      <group>
        {/* <directionalLight position={[10, 10, 10]} />; */}
        {/* <ambientLight intensity={0.6} /> */}
        <group
          ref={group}
          {...props}
          dispose={null}
          scale={0.8}
          rotation-y={-Math.PI}
          // position={[-0.815, 0.855, -0.835]}
        >
          <group name="Scene">
            <group name="Armature" scale={0.01}>
              <skinnedMesh
                frustumCulled={false}
                name="Cube"
                geometry={nodes.Cube.geometry}
                material={materials["Material.006"]}
                skeleton={nodes.Cube.skeleton}
              />
              <group name="Cube001">
                <skinnedMesh
                  frustumCulled={false}
                  name="Cube001_1"
                  geometry={nodes.Cube001_1.geometry}
                  material={materials["Material.005"]}
                  skeleton={nodes.Cube001_1.skeleton}
                />
                <skinnedMesh
                  frustumCulled={false}
                  name="Cube001_2"
                  geometry={nodes.Cube001_2.geometry}
                  material={materials["Material.003"]}
                  skeleton={nodes.Cube001_2.skeleton}
                />
                <skinnedMesh
                  frustumCulled={false}
                  name="Cube001_3"
                  geometry={nodes.Cube001_3.geometry}
                  material={materials["Material.004"]}
                  skeleton={nodes.Cube001_3.skeleton}
                />
                <skinnedMesh
                  frustumCulled={false}
                  name="Cube001_4"
                  geometry={nodes.Cube001_4.geometry}
                  material={materials["Material.007"]}
                  skeleton={nodes.Cube001_4.skeleton}
                />
              </group>
              <group name="Cylinder002">
                <skinnedMesh
                  frustumCulled={false}
                  name="Cylinder002_1"
                  geometry={nodes.Cylinder002_1.geometry}
                  material={materials["Material.005"]}
                  skeleton={nodes.Cylinder002_1.skeleton}
                />
                <skinnedMesh
                  frustumCulled={false}
                  name="Cylinder002_2"
                  geometry={nodes.Cylinder002_2.geometry}
                  material={materials["Material.009"]}
                  skeleton={nodes.Cylinder002_2.skeleton}
                />
                <skinnedMesh
                  frustumCulled={false}
                  name="Cylinder002_3"
                  geometry={nodes.Cylinder002_3.geometry}
                  material={materials["Material.010"]}
                  skeleton={nodes.Cylinder002_3.skeleton}
                />
                <skinnedMesh
                  frustumCulled={false}
                  name="Cylinder002_4"
                  geometry={nodes.Cylinder002_4.geometry}
                  material={materials["Material.011"]}
                  skeleton={nodes.Cylinder002_4.skeleton}
                />
              </group>
              <group name="Göz001">
                <skinnedMesh
                  frustumCulled={false}
                  name="Sphere001"
                  geometry={nodes.Sphere001.geometry}
                  material={materials["Material.012"]}
                  skeleton={nodes.Sphere001.skeleton}
                />
                <skinnedMesh
                  frustumCulled={false}
                  name="Sphere001_1"
                  geometry={nodes.Sphere001_1.geometry}
                  material={materials["Material.013"]}
                  skeleton={nodes.Sphere001_1.skeleton}
                />
                <skinnedMesh
                  frustumCulled={false}
                  name="Sphere001_2"
                  geometry={nodes.Sphere001_2.geometry}
                  material={materials["Material.014"]}
                  skeleton={nodes.Sphere001_2.skeleton}
                />
              </group>
              <skinnedMesh
                frustumCulled={false}
                name="Kafa001"
                geometry={nodes.Kafa001.geometry}
                material={materials.Face}
                skeleton={nodes.Kafa001.skeleton}
              />
              <skinnedMesh
                frustumCulled={false}
                name="Kaş"
                geometry={nodes.Kaş.geometry}
                material={materials.Saç}
                skeleton={nodes.Kaş.skeleton}
              />
              <skinnedMesh
                frustumCulled={false}
                name="Kulak001"
                geometry={nodes.Kulak001.geometry}
                material={materials["Material.002"]}
                skeleton={nodes.Kulak001.skeleton}
              />
              <group name="Plane002">
                <skinnedMesh
                  frustumCulled={false}
                  name="Plane007"
                  geometry={nodes.Plane007.geometry}
                  material={materials["Material.008"]}
                  skeleton={nodes.Plane007.skeleton}
                />
                <skinnedMesh
                  frustumCulled={false}
                  name="Plane007_1"
                  geometry={nodes.Plane007_1.geometry}
                  material={materials["Material.015"]}
                  skeleton={nodes.Plane007_1.skeleton}
                />
              </group>
              <group name="Plane003">
                <skinnedMesh
                  frustumCulled={false}
                  name="Plane009"
                  geometry={nodes.Plane009.geometry}
                  material={materials["Material.008"]}
                  skeleton={nodes.Plane009.skeleton}
                />
                <skinnedMesh
                  frustumCulled={false}
                  name="Plane009_1"
                  geometry={nodes.Plane009_1.geometry}
                  material={materials["Material.015"]}
                  skeleton={nodes.Plane009_1.skeleton}
                />
              </group>
              <skinnedMesh
                frustumCulled={false}
                name="SAç001"
                geometry={nodes.SAç001.geometry}
                material={materials["Material.001"]}
                skeleton={nodes.SAç001.skeleton}
              />
              <primitive object={nodes.mixamorigHips} />
            </group>
          </group>
        </group>
      </group>
    </>
  );
}

useGLTF.preload("models/kid.glb");
