/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: coremort (https://sketchfab.com/coremort)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lowpoly-room-e49f71feb3ea470888993134ce746bd5
Title: Lowpoly Room
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function LowpolyRoom(props) {
  const { nodes, materials } = useGLTF("models/lowpolyRoom.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={2.478}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials["Material.003"]}
        />
      </group>
      <group position={[0.164, -0.996, -2.187]} scale={[0.451, 0.054, 0.208]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_62.geometry}
          material={materials.Comp}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_63.geometry}
          material={materials["Material.007"]}
        />
      </group>
      <group position={[1.192, -1.049, -1.735]} scale={[0.115, 0.03, 0.163]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_65.geometry}
          material={materials.Comp}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_66.geometry}
          material={materials["Material.006"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials.Negrito}
        position={[-2.321, 1.669, 0.029]}
        scale={[0.173, 0.173, 1.636]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials.Gris}
        position={[-2.367, 0.326, 1.51]}
        scale={[0.093, 1.249, 0.056]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_12.geometry}
        material={materials.Gris}
        position={[-2.367, 0.326, -1.562]}
        scale={[0.093, 1.249, 0.056]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_14.geometry}
        material={materials.material_0}
        position={[-2.451, 1.248, -0.035]}
        rotation={[0, 0, -0.728]}
        scale={[0.147, 0.119, 1.519]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_16.geometry}
        material={materials["Material.001"]}
        position={[0.037, -1.872, 1.214]}
        rotation={[0, 1.571, 0]}
        scale={[0.883, 0.25, 1.3]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_18.geometry}
        material={materials.Negrito}
        position={[1.176, -2.28, 0.46]}
        scale={[0.145, 0.215, 0.134]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_20.geometry}
        material={materials.Negrito}
        position={[1.176, -2.28, 1.937]}
        scale={[0.145, 0.215, 0.134]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_22.geometry}
        material={materials.Negrito}
        position={[-1.96, -2.28, 1.834]}
        scale={[0.145, 0.215, 0.134]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_24.geometry}
        material={materials.Negrito}
        position={[-1.96, -2.28, 0.569]}
        scale={[0.145, 0.215, 0.134]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_26.geometry}
        material={materials.material_0}
        position={[-0.968, -1.872, 1.214]}
        rotation={[0, 1.571, 0]}
        scale={[0.807, 0.229, 1.187]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_28.geometry}
        material={materials["Material.005"]}
        position={[-1.663, -1.53, 1.227]}
        scale={[0.399, 0.112, 0.622]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_30.geometry}
        material={materials.material}
        position={[0.028, -1.337, -1.965]}
        scale={[1.72, 0.242, 0.523]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_32.geometry}
        material={materials.Negrito}
        position={[-0.085, -1.859, -0.806]}
        scale={[0.512, 0.077, 0.512]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_34.geometry}
        material={materials.Negrito}
        position={[-0.085, -1.153, -0.288]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.512, 0.077, 0.784]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_36.geometry}
        material={materials.Negrito}
        position={[-0.085, -1.443, -0.806]}
        scale={[0.512, 0.077, 0.512]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_38.geometry}
        material={materials.Negrito}
        position={[-0.092, -2.131, -0.806]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.084, 0.264, 0.084]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_40.geometry}
        material={materials.Negrito}
        position={[0.149, -2.321, -1.025]}
        rotation={[0, 0.751, -Math.PI / 2]}
        scale={[-0.084, 0.264, 0.084]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_42.geometry}
        material={materials.Negrito}
        position={[-0.087, -2.321, -0.586]}
        rotation={[0, 1.563, -1.571]}
        scale={[-0.084, 0.264, 0.084]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_44.geometry}
        material={materials.Negrito}
        position={[-0.357, -2.321, -1.013]}
        rotation={[0, -0.726, -Math.PI / 2]}
        scale={[-0.084, 0.264, 0.084]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_46.geometry}
        material={materials.material_0}
        position={[0.255, -2.427, -1.185]}
        rotation={[Math.PI / 2, 0, -0.726]}
        scale={0.085}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_48.geometry}
        material={materials.material_0}
        position={[-0.5, -2.427, -1.072]}
        rotation={[Math.PI / 2, 0, -2.495]}
        scale={0.085}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_50.geometry}
        material={materials.material_0}
        position={[-0.128, -2.427, -0.427]}
        rotation={[Math.PI / 2, 0, -1.508]}
        scale={0.085}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_52.geometry}
        material={materials.Gris}
        position={[2.075, -2.161, -2.03]}
        scale={0.271}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_54.geometry}
        material={materials.material}
        position={[1.568, -1.975, -1.604]}
        scale={[0.111, 0.503, 0.111]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_56.geometry}
        material={materials.material}
        position={[1.568, -1.975, -2.337]}
        scale={[0.111, 0.503, 0.111]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_58.geometry}
        material={materials.material}
        position={[-1.561, -1.975, -2.337]}
        scale={[0.111, 0.503, 0.111]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_60.geometry}
        material={materials.material}
        position={[-1.561, -1.975, -1.596]}
        scale={[0.111, 0.503, 0.111]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_68.geometry}
        material={materials.Comp}
        position={[0.146, -0.645, -1.66]}
        scale={[0.784, 0.437, 0.784]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_70.geometry}
        material={materials["Material.006"]}
        position={[0.141, -1.039, -1.666]}
        scale={[0.757, 0.278, 0.216]}
      />
    </group>
  );
}

useGLTF.preload("models/lowpolyRoom.glb");
