/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/office.glb 
Author: SeverDoes3D (https://sketchfab.com/SeverDoes3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/office-assets-16c1a779bb0a4055a26367741d39e059
Title: Office - Assets
*/

import React, { useEffect, useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";
import {
  EffectComposer,
  Outline,
  Select,
  Selection,
} from "@react-three/postprocessing";
import { motion } from "framer-motion-3d";

export function Office(props) {
  const { section } = props;
  const { nodes, materials } = useGLTF("models/office.glb");
  const [hovered, setHovered] = useState(false);

  useEffect(() => {
    document.body.style.cursor = hovered ? "pointer" : "auto";
  }, [hovered]);

  return (
    <Selection>
      <EffectComposer multisampling={0} autoClear={false}>
        <Outline
          blur
          visibleEdgeColor="white"
          hiddenEdgeColor="white"
          edgeStrength={10}
          width={1000}
        />
      </EffectComposer>
      <group
        {...props}
        dispose={null}
        rotation={[0, -Math.PI / 3, 0]}
        position={[2.75, -0.5, 2.5]}
        scale={1.5}
      >
        <group
          position={[-0.235, 1.321, 2.261]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.381}
        >
          <mesh
            geometry={nodes.Object_30.geometry}
            material={materials.M_Office_PinBoard_Photo_Notepad_1024}
          />
          <mesh
            geometry={nodes.Object_32.geometry}
            material={materials.M_Office_PinBoard_Photo_Notepad_1024}
            position={[0.433, 0.031, -0.442]}
            rotation={[-0.02, -0.022, 0]}
          />
          <mesh
            geometry={nodes.Object_34.geometry}
            material={materials.M_Office_PinBoard_Photo_Notepad_1024}
            position={[-0.441, 0.037, 0.073]}
            rotation={[-0.032, 0.035, 0]}
          />
          <mesh
            geometry={nodes.Object_36.geometry}
            material={materials.M_Office_PinBoard_Photo_Notepad_1024}
            position={[-0.117, 0.031, -0.374]}
            rotation={[-0.047, -0.054, 0.003]}
          />
          <mesh
            geometry={nodes.Object_38.geometry}
            material={materials.M_Office_PinBoard_Photo_Notepad_1024}
            position={[0.443, 0.03, 0.199]}
            rotation={[-0.068, 0.063, 0.004]}
          />
          <mesh
            geometry={nodes.Object_40.geometry}
            material={materials.M_Office_PinBoard_Photo_Notepad_1024}
            position={[-0.583, 0.03, -0.495]}
            rotation={[-0.034, -0.059, -0.003]}
          />
          <mesh
            geometry={nodes.Object_42.geometry}
            material={materials.M_Office_PinBoard_Photo_Notepad_1024}
            position={[0.192, 0.038, -0.433]}
            rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
            scale={2.627}
          />
          <mesh
            geometry={nodes.Object_44.geometry}
            material={materials.M_Office_PinBoard_Photo_Notepad_1024}
            position={[-0.591, 0.04, -0.475]}
            rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
            scale={2.627}
          />
          <mesh
            geometry={nodes.Object_46.geometry}
            material={materials.M_Office_PinBoard_Photo_Notepad_1024}
            position={[0.683, 0.043, -0.418]}
            rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
            scale={2.627}
          />
          <mesh
            geometry={nodes.Object_48.geometry}
            material={materials.M_Office_PinBoard_Photo_Notepad_1024}
            position={[-0.437, 0.044, 0.092]}
            rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
            scale={2.627}
          />
          <mesh
            geometry={nodes.Object_50.geometry}
            material={materials.M_Office_PinBoard_Photo_Notepad_1024}
            position={[0.483, 0.038, 0.226]}
            rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
            scale={2.627}
          />
          <mesh
            geometry={nodes.Object_52.geometry}
            material={materials.M_Office_PinBoard_Photo_Notepad_1024}
            position={[-0.116, 0.037, -0.358]}
            rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
            scale={2.627}
          />
        </group>
        <group
          position={[0.035, 0.743, 1.904]}
          rotation={[-Math.PI, 1.358, -Math.PI]}
        >
          <mesh
            geometry={nodes.Object_70.geometry}
            material={materials.M_TapeRecorder_1024}
          />
          <mesh
            geometry={nodes.Object_71.geometry}
            material={materials.M_TapeRecorder_Tape_Rotors_Glass_1024}
          />
        </group>
        {/* Lamp */}
        <group
          position={[-0.039, 0.743, 1.563]}
          rotation={[0, 0.454, 0]}
          scale={[1, 1, 1]}
        >
          <group position={[0, 0.061, 0]} rotation={[0, 0, 0.811]}>
            <group position={[0, 0.118, 0]} rotation={[0, 0, -0.976]}>
              <group position={[0, 0.279, 0]} rotation={[0, 0, -0.491]}>
                <group position={[0, 0.366, 0]} rotation={[0, 0, -0.603]}>
                  <mesh
                    geometry={nodes.Object_117.geometry}
                    material={materials["M_Lamps_CCTV_2048.001"]}
                  />
                  <mesh
                    geometry={nodes.Object_119.geometry}
                    material={materials["M_Lamps_CCTV_2048.001"]}
                    position={[0, 0.083, 0]}
                  />
                </group>
                <mesh
                  geometry={nodes.Object_115.geometry}
                  material={materials["M_Lamps_CCTV_2048.001"]}
                />
              </group>
              <mesh
                geometry={nodes.Object_113.geometry}
                material={materials["M_Lamps_CCTV_2048.001"]}
              />
            </group>
            <mesh
              geometry={nodes.Object_111.geometry}
              material={materials["M_Lamps_CCTV_2048.001"]}
            />
          </group>
          <mesh
            geometry={nodes.Object_109.geometry}
            material={materials["M_Lamps_CCTV_2048.001"]}
          />
        </group>
        {/* Table */}
        <motion.group>
          {/* Computer */}

          <mesh
            geometry={nodes.Object_10.geometry}
            material={materials.M_Computer_2048}
            position={[0.488, 0.743, 0.925]}
            rotation={[0, 0.168, 0]}
          />
          <mesh
            geometry={nodes.Object_12.geometry}
            material={materials.M_Computer_2048}
            position={[0.533, 0.743, 0.53]}
            rotation={[0, -0.169, 0]}
          />
          <mesh
            geometry={nodes.Object_14.geometry}
            material={materials.M_Computer_2048}
            position={[0.061, 0.743, 0.472]}
            rotation={[0, -0.387, 0]}
          />
          <Select enabled={hovered}>
            <mesh
              onPointerOver={() => setHovered(true)}
              onPointerOut={() => setHovered(false)}
              geometry={nodes.Object_16.geometry}
              material={materials.M_Computer_2048}
              position={[0.103, 0.91, 0.502]}
              rotation={[0, -0.269, 0]}
            ></mesh>
          </Select>
          {/* FileBox */}
          <mesh
            geometry={nodes.Object_18.geometry}
            material={materials.M_Filebox_1024}
            position={[-0.084, 0.743, 1.283]}
            rotation={[0, 1.531, 0]}
            scale={[1.096, 1, 1]}
          />
          <mesh
            geometry={nodes.Object_20.geometry}
            material={materials.M_Filebox_1024}
            position={[-0.075, 0.743, 1.398]}
            rotation={[-Math.PI, 1.512, -Math.PI]}
            scale={[1.096, 1, 1]}
          />
          <mesh
            geometry={nodes.Object_22.geometry}
            material={materials.M_Filebox_1024}
            position={[-0.084, 0.743, 1.281]}
            rotation={[0, 1.531, 0]}
            scale={[1.096, 1, 1]}
          />
          <mesh
            geometry={nodes.Object_24.geometry}
            material={materials.M_Filebox_1024}
            position={[-0.075, 0.743, 1.398]}
            rotation={[-Math.PI, 1.512, -Math.PI]}
            scale={[1.096, 1, 1]}
          />

          <mesh
            geometry={nodes.Object_68.geometry}
            material={materials.M_Table_2048}
            position={[0.213, 0.006, 1.171]}
          />
          <mesh
            geometry={nodes.Object_73.geometry}
            material={materials.M_TapeRecorder_Tape_Rotors_Glass_1024}
            position={[0.445, 0.743, 1.958]}
            rotation={[0, 0.361, 0]}
          />
          <mesh
            geometry={nodes.Object_95.geometry}
            material={materials.Poster_1024}
            position={[-0.246, 1.568, 1.317]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            scale={[0.619, 0.309, 0.619]}
          />
          <mesh
            geometry={nodes.Object_105.geometry}
            material={materials.M_Clipboard_Notepad_1024}
            position={[0.235, 0.743, 1.171]}
            rotation={[0, 0.319, Math.PI / 2]}
          />
          <mesh
            geometry={nodes.Object_107.geometry}
            material={materials.M_OfficeStool_Bin_2048}
            position={[1.055, 0.008, 1.05]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={[1.235, 1, 1.235]}
          />
        </motion.group>
      </group>
    </Selection>
  );
}

useGLTF.preload("/office.glb");
