/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: daydev (https://sketchfab.com/daydev)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/librarians-room-5363dd8100c64cb2a99b5619b7d78610
Title: Librarian's Room
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Room(props) {
  const { nodes, materials } = useGLTF("models/room.glb");
  return (
    <group {...props} dispose={null} scale={0.08}>
      <group
        position={[12.096, 11.584, -59.541]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={194.179}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Room_Wall_0.geometry}
          material={materials.Wall}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Room_Floor_0.geometry}
          material={materials.Floor}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Room_Windows_0.geometry}
          material={materials.Windows}
        />
      </group>
      <group
        position={[-101.408, -101.92, -175.955]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={47.299}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_Bed_0.geometry}
          material={materials.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_Bed2_0.geometry}
          material={materials.Bed2}
        />
      </group>
      <group
        position={[118.938, 77.76, -199.278]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={21.466}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Book_BookA_0.geometry}
          material={materials.BookA}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Book_Paper_0.geometry}
          material={materials.Paper}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Book_CoverA_0.geometry}
          material={materials.CoverA}
        />
      </group>
      <group
        position={[127.024, 73.743, -199.278]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={18.48}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Book001_BookB_0.geometry}
          material={materials.BookB}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Book001_Paper_0.geometry}
          material={materials.Paper}
        />
      </group>
      <group
        position={[137.579, 74.486, -199.278]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={18.48}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Book002_BookC_0.geometry}
          material={materials.BookC}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Book002_Paper_0.geometry}
          material={materials.Paper}
        />
      </group>
      <group
        position={[153.833, 74.486, -199.278]}
        rotation={[-Math.PI / 2, -0.377, Math.PI / 2]}
        scale={18.48}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Book003_BookD_0.geometry}
          material={materials.BookD}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Book003_Paper_0.geometry}
          material={materials.Paper}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Book003_CoverA_0.geometry}
          material={materials.CoverA}
        />
      </group>
      <group
        position={[195.574, 58.736, -199.278]}
        rotation={[Math.PI, -1.073, 0]}
        scale={18.48}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Book004_Paper_0.geometry}
          material={materials.Paper}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Book004_CoverB_0.geometry}
          material={materials.CoverB}
        />
      </group>
      <group
        position={[5.323, -69.051, -52.437]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={162.888}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane_Cloth_0.geometry}
          material={materials.Cloth}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane_ClothB_0.geometry}
          material={materials.ClothB}
        />
      </group>
      <group
        position={[136.249, -43.814, -191.086]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={31.477}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_Computer_0.geometry}
          material={materials.Computer}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_Mac_0.geometry}
          material={materials.material_17}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_Black_0.geometry}
          material={materials.Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_Keyboard_0.geometry}
          material={materials.Keyboard}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_Desktop_0.geometry}
          material={materials.Desktop}
        />
      </group>
      <group
        position={[-153.456, 138.613, -31.457]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={[291.269, 194.179, 93.206]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.VenetianFrame_Plastic_venetian_material_0.geometry}
          material={materials.Plastic_venetian_material}
        />
        <group position={[0, 0, -0.08]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Venetian_slats_Plastic_venetian_material_0.geometry}
            material={materials.Plastic_venetian_material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.StringL_String_material_0.geometry}
            material={materials.String_material}
            position={[0.352, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.StringC_String_material_0.geometry}
            material={materials.String_material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.StringR_String_material_0.geometry}
            material={materials.String_material}
            position={[-0.352, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.StringfL_String_material_0.geometry}
            material={materials.String_material}
            position={[0.352, -0.021, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.StringfC_String_material_0.geometry}
            material={materials.String_material}
            position={[0, -0.021, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.StringfR_String_material_0.geometry}
            material={materials.String_material}
            position={[-0.352, -0.021, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.StringbL_String_material_0.geometry}
            material={materials.String_material}
            position={[0.352, 0.021, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.StringbC_String_material_0.geometry}
            material={materials.String_material}
            position={[0, 0.021, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.StringbR_String_material_0.geometry}
            material={materials.String_material}
            position={[-0.352, 0.021, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Venetian_base_Plastic_venetian_material_0.geometry}
            material={materials.Plastic_venetian_material}
            position={[0, 0, -1.59]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Venetian_stick__0.geometry}
          material={materials["Cube.002__0"]}
          position={[-0.47, -0.023, -0.03]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Venetian_updown_String_material_0.geometry}
          material={materials.String_material}
          position={[0.47, -0.023, -0.03]}
        />
      </group>
      <group
        position={[203.649, -58.793, -230.692]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={161.17}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Book0_Book0_material_0.geometry}
          material={materials.Book0_material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Book0_Book0_side_material_0.geometry}
          material={materials.Book0_side_material}
        />
      </group>
      <group
        position={[210.934, -58.793, -230.692]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={161.17}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Book1_Book1_material_0.geometry}
          material={materials.Book1_material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Book1_Book1_side_material_0.geometry}
          material={materials.Book1_side_material}
        />
      </group>
      <group
        position={[218.219, -58.793, -230.692]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={161.17}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Book2_Book2_material_0.geometry}
          material={materials.Book2_material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Book2_Book2_side_material_0.geometry}
          material={materials.Book2_side_material}
        />
      </group>
      <group
        position={[225.504, -58.793, -230.692]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={161.17}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Book3_Book3_material_0.geometry}
          material={materials.Book3_material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Book3_Book3_side_material_0.geometry}
          material={materials.Book3_side_material}
        />
      </group>
      <group
        position={[232.789, -58.793, -230.692]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={161.17}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Book4_Book4_material_0.geometry}
          material={materials.Book4_material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Book4_Book4_side_material_0.geometry}
          material={materials.Book4_side_material}
        />
      </group>
      <group
        position={[-143.294, 64.03, -218.151]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={416.126}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Lampholder_Lampholder_material_0.geometry}
          material={materials.Lampholder_material}
        />
        <group position={[0, 0, 0.03]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Lampstrings_Lampstrings_material_0.geometry}
            material={materials.Lampstrings_material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Lamp_B1_Lampstrings_material_0.geometry}
            material={materials.Lampstrings_material}
            position={[0.021, 0, 0.035]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Lamp_B2_Lampstrings_material_0.geometry}
            material={materials.Lampstrings_material}
            position={[-0.021, 0, 0.035]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Lamp_Bulb001_Lamp_Bulb_0.geometry}
          material={materials.Lamp_Bulb}
          position={[0, 0, 0.091]}
        />
      </group>
      <group
        position={[223.21, -55.841, -155.996]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={194.179}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Lamp_base_Lamp_base_material001_0.geometry}
          material={materials["Lamp_base_material.001"]}
        />
        <group position={[0, 0, 0.15]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Lampholder001_Lampholder001_material_0.geometry}
            material={materials["Lampholder.001_material"]}
          />
          <group position={[0, 0, 0.03]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Lampstrings001_Lampstrings001_material_0.geometry}
              material={materials["Lampstrings.001_material"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Lamp_B1001_Lampstrings001_material_0.geometry}
              material={materials["Lampstrings.001_material"]}
              position={[0.021, 0, 0.035]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Lamp_B2001_Lampstrings001_material_0.geometry}
              material={materials["Lampstrings.001_material"]}
              position={[-0.021, 0, 0.035]}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Lamp_Bulb_Lamp_Bulb001_0.geometry}
            material={materials["Lamp_Bulb.001"]}
            position={[0, 0, 0.091]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Lampshade001_Lampshade001_material_0.geometry}
          material={materials["Lampshade.001_material"]}
          position={[0, 0, 0.181]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Table_Table_0.geometry}
        material={materials.Table}
        position={[169.704, -114.937, -229.054]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={8.501}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001_Table_0.geometry}
        material={materials.Table}
        position={[171.999, 46.083, -202.247]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={29.376}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002__0.geometry}
        material={materials["Cube.002__0"]}
        position={[-118.973, -68.756, -188.596]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={23.36}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003__0.geometry}
        material={materials["Cube.002__0"]}
        position={[-58.308, -55.237, -188.596]}
        rotation={[-Math.PI / 2, 0.246, 0.557]}
        scale={23.36}
      />
    </group>
  );
}

useGLTF.preload("models/room.glb");
